name: Run Automation Script

on:
  schedule:
    - cron: '0 0 * * *'  # This runs the script every hour
  workflow_dispatch:
  
env:
  API_TOKEN: ${{ secrets.API_TOKEN }}  # Access the secret securely


jobs:
  run-python-script: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: upgrade pip 
      run: | 
            python -m pip install --upgrade pip
            pip install -r requirements.txt

    - name: Run script
      run: python main.py

    - name: Commit updated ids_count.json
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add ids_count.json && git commit -n -m 'Update ids_count.json' || true  # Skip if no changes
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit main.log
      run: |
        git add main.log && git commit -n -m 'Update main.log' || true  # Skip if no changes
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
